/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RealmRouteImport } from './routes/realm'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as DenRouteImport } from './routes/den'
import { Route as IndexRouteImport } from './routes/index'

const RealmRoute = RealmRouteImport.update({
  id: '/realm',
  path: '/realm',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const DenRoute = DenRouteImport.update({
  id: '/den',
  path: '/den',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/den': typeof DenRoute
  '/diary': typeof DiaryRoute
  '/finance': typeof FinanceRoute
  '/planner': typeof PlannerRoute
  '/realm': typeof RealmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/den': typeof DenRoute
  '/diary': typeof DiaryRoute
  '/finance': typeof FinanceRoute
  '/planner': typeof PlannerRoute
  '/realm': typeof RealmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/den': typeof DenRoute
  '/diary': typeof DiaryRoute
  '/finance': typeof FinanceRoute
  '/planner': typeof PlannerRoute
  '/realm': typeof RealmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/den' | '/diary' | '/finance' | '/planner' | '/realm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/den' | '/diary' | '/finance' | '/planner' | '/realm'
  id: '__root__' | '/' | '/den' | '/diary' | '/finance' | '/planner' | '/realm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DenRoute: typeof DenRoute
  DiaryRoute: typeof DiaryRoute
  FinanceRoute: typeof FinanceRoute
  PlannerRoute: typeof PlannerRoute
  RealmRoute: typeof RealmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/realm': {
      id: '/realm'
      path: '/realm'
      fullPath: '/realm'
      preLoaderRoute: typeof RealmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/den': {
      id: '/den'
      path: '/den'
      fullPath: '/den'
      preLoaderRoute: typeof DenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DenRoute: DenRoute,
  DiaryRoute: DiaryRoute,
  FinanceRoute: FinanceRoute,
  PlannerRoute: PlannerRoute,
  RealmRoute: RealmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
